export const scholarships = [
  {
    name: 'Stipendium Hungaricum',
    country: 'Hungary',
    degreeLevel: "Bachelor's",
    fields: ['Medicine', 'Engineering', 'Business', 'AI'],
    fundingCoverage: 'Full tuition, stipend, accommodation, insurance',
    fullyFunded: true,
    ieltsRequirement: 'Optional',
    englishProofs: ['IELTS', 'TOEFL', 'MOI'],
    minGPA: 70,
    deadline: '2027-01-15',
    officialLink: 'https://stipendiumhungaricum.hu/',
    description: 'Government scholarship for international students.'
  },
  {
    name: 'Chinese Government Scholarship (CSC)',
    country: 'China',
    degreeLevel: "Bachelor's",
    fields: ['Engineering', 'Medicine', 'Business', 'AI'],
    fundingCoverage: 'Tuition, accommodation, stipend, medical insurance',
    fullyFunded: true,
    ieltsRequirement: 'No',
    englishProofs: ['MOI'],
    minGPA: 75,
    deadline: '2027-03-31',
    officialLink: 'https://www.campuschina.org/',
    description: 'National scholarship offered through Chinese universities.'
  },
  {
    name: 'Türkiye Burslari',
    country: 'Turkey',
    degreeLevel: "Bachelor's",
    fields: ['Engineering', 'Business', 'Social Sciences', 'Medicine'],
    fundingCoverage: 'Tuition, stipend, accommodation, health insurance, flights',
    fullyFunded: true,
    ieltsRequirement: 'No',
    englishProofs: ['MOI'],
    minGPA: 70,
    deadline: '2027-02-20',
    officialLink: 'https://www.turkiyeburslari.gov.tr/',
    description: 'Highly competitive scholarship by the Turkish government.'
  },
  {
    name: 'Italian DSU Scholarship',
    country: 'Italy',
    degreeLevel: "Bachelor's",
    fields: ['Engineering', 'Business', 'Arts', 'Computer Science'],
    fundingCoverage: 'Tuition waiver, accommodation support, meal subsidy',
    fullyFunded: true,
    ieltsRequirement: 'Optional',
    englishProofs: ['MOI', 'IELTS'],
    minGPA: 65,
    deadline: '2027-09-01',
    officialLink: 'https://www.dsu.toscana.it/',
    description: 'Regional need-based support in Italian universities.'
  },
  {
    name: 'Kazakhstan Government Scholarship',
    country: 'Kazakhstan',
    degreeLevel: "Bachelor's",
    fields: ['Engineering', 'AI', 'Business', 'Agriculture'],
    fundingCoverage: 'Tuition and monthly stipend',
    fullyFunded: true,
    ieltsRequirement: 'No',
    englishProofs: ['MOI'],
    minGPA: 60,
    deadline: '2027-07-30',
    officialLink: 'https://enic-kazakhstan.edu.kz/en/post/171',
    description: 'Scholarship program for foreign nationals.'
  },
  {
    name: 'TaiwanICDF Scholarship',
    country: 'Taiwan',
    degreeLevel: "Bachelor's",
    fields: ['Agriculture', 'Public Health', 'Engineering', 'Business'],
    fundingCoverage: 'Tuition, airfare, housing, insurance, stipend',
    fullyFunded: true,
    ieltsRequirement: 'Optional',
    englishProofs: ['IELTS', 'TOEFL', 'MOI'],
    minGPA: 70,
    deadline: '2027-03-15',
    officialLink: 'https://www.icdf.org.tw/',
    description: 'International scholarship and development program.'
  }
];
